name: react

description: |
  Example component that includes a React frontend that integrates with an an Architect dependency for the backend

homepage: https://github.com/architect-templates/react

keywords:
  - react
  - express

dependencies:
  node-rest-api: latest

services:
  app:
    build:
      context: ./
      args:
        NODE_ENV: production
    interfaces:
      main:
        port: 8080
        ingress:
          subdomain: app
    environment:
      PORT: 8080
      REACT_APP_API_ADDR: ${{ dependencies.node-rest-api.services.api.interfaces.main.ingress.url }}
    debug:
      command: npm run dev
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          mount_path: /usr/src/app/src
          host_path: ./src
